# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/kamil/catkin_ws/src/ardrone_autonomy/msg/matrix33.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_adc_data_frame.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_altitude.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_demo.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_euler_angles.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_games.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_gyros_offsets.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_hdvideo_stream.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_kalman_pressure.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_magneto.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/Navdata.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_phys_measures.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_pressure_raw.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_pwm.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_raw_measures.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_rc_references.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_references.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_time.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_trackers_send.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_trims.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_video_stream.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_vision_detect.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_vision.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_vision_of.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_vision_perf.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_vision_raw.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_watchdog.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_wifi.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_wind_speed.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/navdata_zimmu_3000.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/vector21.msg;/home/kamil/catkin_ws/src/ardrone_autonomy/msg/vector31.msg"
services_str = "/home/kamil/catkin_ws/src/ardrone_autonomy/srv/CamSelect.srv;/home/kamil/catkin_ws/src/ardrone_autonomy/srv/FlightAnim.srv;/home/kamil/catkin_ws/src/ardrone_autonomy/srv/LedAnim.srv;/home/kamil/catkin_ws/src/ardrone_autonomy/srv/RecordEnable.srv"
pkg_name = "ardrone_autonomy"
dependencies_str = "geometry_msgs;std_msgs"
langs = "gencpp;genlisp;genpy"
dep_include_paths_str = "ardrone_autonomy;/home/kamil/catkin_ws/src/ardrone_autonomy/msg;geometry_msgs;/opt/ros/indigo/share/geometry_msgs/cmake/../msg;std_msgs;/opt/ros/indigo/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/indigo/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
